# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run scraping
      run: |
        python3 scrap.py
        
    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: 'Łukasz Kałużny'
        author_email: lukasz@kaluzny.pro
        message: 'New scraping'
        add: '*.json'
